#!/usr/bin/env python3

import os
import sys
import requests
from operator import itemgetter

try:
    from lxml import html
except ImportError:
    print('error: lxml is not installed (hint: pip install lxml)')
    exit()

# grab movies, tv shows, and anime (sort by seeder count)
# might add flags to only search in certain categories (movies, tv, anime)

# can be changed to a mirror, might automate switching mirrors if 
# server doesn't respond or something
base_url = 'https://1337x.wtf'

responses = []

def main():

    # checks if webtorrent and mpv are installed in /usr/bin/
    flag = 0
    if not os.path.exists('/usr/bin/webtorrent'):
        print('error: webtorrent-cli is not installed')
        flag += 1
    if not os.path.exists('/usr/bin/mpv'):
        print('error: mpv is not installed')
        flag += 1
    if flag > 0:
        print('exiting cthulhu...')
        exit()

    # creates /home/$USER/.cache/cthulhu/ (not needed for now)
    """ os.makedirs(os.path.expanduser('~')+'/.cache/cthulhu', exist_ok=True)
    cache_dir = os.path.expanduser('~')+'/.cache/cthulhu' """

    # parsing arguments
    args = sys.argv
    parsed_args = parse_args(args)


    # parsing html responses from search query
    final_results = parse_responses()
    
    # displays results for requesting magnet link 
    magnet_link = get_magnet_link(final_results, display_count=20)

    if not 'get-magnet' in parsed_args:
        # play selected torrent in webtorrent
        os.system(f'peerflix --mpv -a \'{magnet_link}\'')

        # cleans /tmp/webtorrent directory if specified by --no-clean
        print('Cleaning /tmp/webtorrent...')
        if 'no-clean' in parsed_args:
            os.system('rm -rf /tmp/webtorrent')
    else: 
        print(magnet_link)
 

def parse_args(args):

    parsed_args = []

    # TODO implement flags --fast...--no-clean
    """
    flags:
    -h, --help
    --fast 
    -m, --movie
    -s, --show
    -a, --anime
    --no-clean
    --get-magnet
    """

    flags = ['-h', '--help', '--fast', '-m', '--movie', '-s', '--show', '-a', '--anime', '--no-clean', '--get-magnet']

    def get_query(filtering='default'):
        query = ''
        for i in range(1, len(args)):
            if args[i] not in flags:
                query += args[i]
                if i != len(args)-1:
                    query += '+'       
        if query != '':
            search(query, filtering)
        else:
            query = input('Enter search query: ')
            search(query, filtering)

    # the below if-else tree is dogshit, I will admit. Very slow.
    # the thing is, even if it's slow, it's still very fast
    # which makes it very cool, and not my problem

    searched = False

    if len(args) == 1:
        get_query()
    else:
        # -h, --help
        if flags[0] in args or flags[1] in args:
            help()
        # --fast
        if flags[2] in args:
            if not searched:
                get_query(filtering='fast')
                searched = True
        # -m, --movie
        if flags[3] in args or flags[4] in args:
            if not searched:
                get_query(filtering='movie')
                searched = True
        # -s, --show
        if flags[5] in args or flags[6] in args:
            if not searched:
                get_query(filtering='show')
                searched = True
        # -a, --anime
        if flags[7] in args or flags[8] in args:
            if not searched:
                get_query(filtering='anime')
                searched = True
        # --no-clean
        if flags[9] in args:
            parsed_args.append('no-clean')
        # --get-magnet
        if flags[10] in args:
            parsed_args.append('get-magnet')
        
    if not searched:
        get_query()


    return parsed_args


def search(search_query, filtering):

    #while int(selection) not in range(1, display_count+1):
    #    print('Selection out of range, please try again')
    #    selection = input('\nSelect by number: ')

    while len(search_query) < 3:
        print('Please make sure your query contains at least 3 characters')
        search_query = input('\nEnter search query: ')
    print('Receiving response...', end=' ')
    if filtering == 'default':
        print()
        responses.append(requests.get(f'{base_url}/category-search/{search_query}/Movies/1/').text)
        responses.append(requests.get(f'{base_url}/category-search/{search_query}/TV/1/').text)
        responses.append(requests.get(f'{base_url}/category-search/{search_query}/Anime/1/').text)
    elif filtering == 'fast':
        print('Displaying non-filtered results')
        responses.append(requests.get(f'{base_url}/search/{search_query}/1/').text)
    elif filtering == 'movie':
        print('Displaying movies only:')
        responses.append(requests.get(f'{base_url}/category-search/{search_query}/Movies/1/').text)
    elif filtering == 'show':
        print('Displaying shows only:')
        responses.append(requests.get(f'{base_url}/category-search/{search_query}/TV/1/').text)
    elif filtering == 'anime':
        print('Displaying anime only:')
        responses.append(requests.get(f'{base_url}/category-search/{search_query}/Anime/1/').text)
    print()


def help():
    # TODO help function
    exit()


def parse_responses():

    packed_data = []
    titles = []
    seeders = []
    leechers = []
    upload_dates = []
    file_sizes = []
    links = []

    flag = 0
    num_response = 0
    for response in responses:
        
        num_response += 1
        
        root = html.fromstring(response).xpath('//tbody/tr')

        if not root:
            flag += 1

        for tr in root:
            # title
            tmp_title = tr.xpath('.//td//a/text()')[0]

            # torrent link
            tmp_torrent_link = tr.xpath('.//td//a/@href')[1]

            # [seeders, leechers, upload date, size]
            tmp_additional_data = tr.xpath('.//td/text()')

            titles.append(tmp_title)
            seeders.append(int(tmp_additional_data[0]))
            leechers.append(int(tmp_additional_data[1]))
            upload_dates.append(tmp_additional_data[2])
            file_sizes.append(tmp_additional_data[3])
            links.append(tmp_torrent_link)

    if flag == num_response:
        print('No results found\n')
        exit()

    for i in range(len(titles)):
        packed_data.append([titles[i], links[i], upload_dates[i], seeders[i], leechers[i], file_sizes[i]])

    # sort by seeder count
    sorted_data = sorted(packed_data, key=itemgetter(3), reverse=True)

    return sorted_data


def get_magnet_link(results, display_count):

    if display_count>len(results):
        display_count = len(results)
    
    # display data to user
    print('\033[0mNum\t    S/L\t\tTorrent Name\033[0m')
    title_width = 0
    if os.get_terminal_size()[0] > 24:
        title_width = os.get_terminal_size()[0]-25
    for i in range(display_count): 
        torrent_name = results[i][0]
        if len(torrent_name) > title_width:
            torrent_name = torrent_name[0:title_width-3]+'...'
        seedleech = f'(S:{results[i][3]}, L:{results[i][4]})'
        print(' \033[1m{:>2}\033[0m\t{:>5}/{:<5}\t{}'.format(i+1, results[i][3], results[i][4], torrent_name))

    selection = input('\nSelect by number: ')
    while int(selection) not in range(1, display_count+1):
        print('Selection out of range, please try again')
        selection = input('\nSelect by number: ')

    target_link = f'{base_url}{results[int(selection)-1][1]}'
    magnet_response = requests.get(target_link).text

    magnet_link = html.fromstring(magnet_response).xpath('//li/a/@href')[29]

    return magnet_link


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print(' Interrupted')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
